---
abstract: 'Feature-complete Cucumber-style testing in Perl'
author:
  - "['Peter Sergeant <pete@clueball.com>','Ben Rogers <ben@bdr.org>']"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-BDD-Cucumber
requires:
  Clone: '0'
  File::Find::Rule: '0'
  File::Slurp: '0'
  FindBin::libs: '0'
  Getopt::Long: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Method::Signatures: '0'
  Moose: '0'
  Ouch: '0'
  Path::Class: '0'
  Storable: '0'
  Term::ANSIColor: '3.00'
  Test::Builder: '0'
  Test::Differences: '0'
  Test::More: '0'
  YAML::Syck: '0'
version: '0.18'
